name: Magisk Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Magisk Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build release
        run: ./build.py -vr all

      - name: Build debug
        run: ./build.py -v all

      - name: Stop Gradle daemon
        run: ./gradlew --stop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: magisk-build-${{ github.sha }}
          path: out/
